name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - run: npm i
        working-directory: ./backend

      - run: npm run build
        working-directory: ./backend

      - name: Create .env
        run: echo ${{ secrets.env }} > ./.env
        working-directory: ./backend

      - name: Deploy
        run: |
          pm2 stop biller || true
          pm2 delete biller || true
          pm2 start ./dist/backend/main.js --name biller
        working-directory: ./backend
